navigation: 
  - url: '#'
    title: Link 1
  - url: '#'
    title: Link 2
  - url: '#'
    title: Link 3
  - url: '#'
    title: Link 4
  - url: '#'
    title: Link 5
  - url: '#'
    title: Link 6
brands:
  - title: Customized Menus
  - title: Mindful Cooking
  - title: Personal Chef
  - title: Artistic Presentation
  - title: Dietary Expertise
  - title: Ayurvedic Fusion